### ISSUE TITLE
librfxencode.la dependency_libs issue when packaging devel for Debian

### ISSUE THREAD

**Issue by RussellAult** [neutrinolabs/librfxcodec#1]
When packaging the `devel` branch for Debian, `lintian` throws an error about `librfxencode.la`'s `dependency_libs` being wrong. Because Debian packages install to `/usr`, a `prefix=/usr` flag has to be supplied to `make` instruction. This causes the outputted `librfxencode.la` to list `dependency_libs='-L/usr/lib'`, which is what is causing the `lintian` error.

I'm definitely a novice when it comes to packaging, but I discovered that removing line `28` from `src/Makefile.am` seems to have resolved the problem, and it doesn't seem to have caused others. (I tried altering the line, which, given my lack of `automake` knowledge, only served to throw more serious errors, although removing it entirely seems to have had the desired effect.) Is there a way this line could be re-written so that it doesn't throw errors?

Thanks!

-Russ

**Comment by proski** [comment]
I agree, GOT_PREFIX is evil. Prefix should be used for installation, not for search for other packages. There are standard ways to specify library and include path. My pull request #3 removes GOT_PREFIX. Please review it.

In the future, please refer to the line contents, not to its number. Line numbers change much more often than their contents. Or at least provide a link to a specific revision of the file.

**Comment by proski** [comment]
My patch has been merged. I have verified that `-L/usr/lib` is not used during compilation when the prefix is `/usr`. I consider this issue resolved.

**Comment by metalefty** [comment]
Let's close after xrdp's submodule updated.
