### ISSUE TITLE
Possible typo in rfxencode_rgb_to_yuv.c

### ISSUE THREAD

**Issue by dartraiden** [neutrinolabs/librfxcodec#42]
https://github.com/neutrinolabs/librfxcodec/blob/ef68593b7d19c89cff2a2d27c6ab3cc5f33611da/src/rfxencode_rgb_to_yuv.c#L89
```
*lr_buf++ = r;
*lg_buf++ = g;
*lb_buf++ = r;
```

https://github.com/neutrinolabs/librfxcodec/blob/ef68593b7d19c89cff2a2d27c6ab3cc5f33611da/src/rfxencode_rgb_to_yuv.c#L263
```
*la_buf++ = a;
*lr_buf++ = r;
*lg_buf++ = g;
*lb_buf++ = r;
```

probably should be *b* instead of *r*

**Comment by jsorg71** [comment]
Yes, I think you are right :)
Normal use can for librfxcodec is to pass in YUV so that explains why we didn't catch it.
Thanks, I'll fix it.

**Comment by jsorg71** [comment]
I created #44

**Comment by metalefty** [comment]
What types of glitches does this typo cause?

**Comment by jsorg71** [comment]
Nothing you can see.  This is in the tile padding.  The tiles must be 64x64 so this is used at the right and bottom of an image.  This done wrong should mean the compressed size is a bit higher.  Also, this color conversion does not happen in normal xrdp use as xorgxrdp does the color conversion and alignment.
