### ISSUE TITLE
configure failed for librfxcodec

### ISSUE THREAD

**Issue by Steveorevo** [neutrinolabs/librfxcodec#43]
This issue still occurs on macOS when building xrdp following documented build instructions.

https://github.com/neutrinolabs/xrdp/issues/1138

**Comment by rogeroger-yu** [comment]
I tried multiple versions of configure on macos, all of which are the same error.
"installation or configuration problem: assembler canot create object files."

**Comment by metalefty** [comment]
https://github.com/neutrinolabs/xrdp/issues/1138#issuecomment-395005726

**Comment by rogeroger-yu** [comment]
> [neutrinolabs/xrdp#1138 (comment)](https://github.com/neutrinolabs/xrdp/issues/1138#issuecomment-395005726)

I came from that issue and noticed that you gave a jump link on both sides.I am not sure if you want to solve this problem or to shirk it.
