### ISSUE TITLE
Add progressive RFX encoding for GFX

### ISSUE THREAD

**Issue by jsorg71** [neutrinolabs/librfxcodec#45]
part of MS-RDPEGFX
description here
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/f8c3c134-bf99-45eb-be7e-d22c8178255f

**Comment by jsorg71** [comment]
Got progressive working using simple tiles for now but tile diffing works.  I can see the bandwidth reduction when it's on.

**Comment by Nexarian** [comment]
Does https://github.com/neutrinolabs/librfxcodec/pull/50 resolve this?

**Comment by metalefty** [comment]
I believe so.
