### ISSUE TITLE
scanline like effect with gfx progressive

### ISSUE THREAD

**Issue by akarl10** [neutrinolabs/librfxcodec#54]
I don't know if it is really librfxcodec to blame, but since rfx progressive is implemented the colors are not correct any more
the cli parameters used in ex freerdp are /gfx +gfx-progressive. If I use /rfx or /gfx:avc444 it look correct

![grafik](https://user-images.githubusercontent.com/3184745/199088761-c7cb9d70-292b-4e03-bfa4-8692fc3994f2.png)
the black/dark gray should be solid without the horizontal lines

**Comment by jsorg71** [comment]
I think the problem may be xorgxrdp, can you try this patch.
```
diff --git a/module/rdpCapture.c b/module/rdpCapture.c
index 94f16aa..8ebfa66 100644
--- a/module/rdpCapture.c
+++ b/module/rdpCapture.c
@@ -1170,7 +1170,14 @@ rdpCapture2(rdpClientCon *clientCon, RegionPtr in_reg, BoxPtr *out_rects,
             rcode = rdpRegionContainsRect(in_reg, &rect);
             LLOGLN(10, ("rdpCapture2: rcode %d", rcode));

-            if (rcode != rgnOUT)
+            if (rcode == rgnOUT)
+            {
+                LLOGLN(0, ("rdpCapture2: rgnOUT"));
+                rdpRegionInit(&tile_reg, &rect, 0);
+                rdpRegionSubtract(in_reg, in_reg, &tile_reg);
+                rdpRegionUninit(&tile_reg);
+            }
+            else
             {
                 crc = crc_start();
                 if (rcode == rgnPART)
```

**Comment by akarl10** [comment]
it may also be that xorgxrdp ist the culprit (considering that the login screen is ok).
with this patch however the screen is black/no output.
where is the place I may open a bug report or at least report back? afaik the devel branch of xorgxrdp and xrdp do not have egfx (I am on Nexarians mainline_merge)

**Comment by akarl10** [comment]
> it may also be that xorgxrdp ist the culprit (considering that the login screen is ok). with this patch however the screen is black/no output. where is the place I may open a bug report or at least report back? afaik the devel branch of xorgxrdp and xrdp do not have egfx (I am on Nexarians mainline_merge)

sorry, the screen did not go black. It was a issue on my side. but the patch did not fix it

**Comment by jsorg71** [comment]
@akarl10 thanks, can you provide what it should look like?

**Comment by akarl10** [comment]
sure (with /rfx):
![grafik](https://user-images.githubusercontent.com/3184745/199190471-3643b2e7-74ad-4e33-ae82-ec76ec7b44ff.png)

don't know if plasma uses colors that don't work well with rfxpro, but I never saw this when connecting to a windows machine

**Comment by jsorg71** [comment]
Oh, I see now.
Progressive is using more aggressive quantifier settings. Setting them the same should fix it.  Can you try that, it's in xrdp_encoder.c, g_rfx_quantization_values

RFX is using the encoder's defaults which is 0x66, 0x66, 0x77, 0x88, 0x98 for all tiles, y, u, and v
Pro is using the above for y and 0x76, 0x77, 0x88, 0x98, 0xA9 for u and v
Higher numbers means you throw out more bits.

**Comment by akarl10** [comment]
ok, you are right, changing this values does indeed change the output.

if I set
```
static const unsigned char g_rfx_quantization_values[] =
{
    0x66, 0x66, 0x77, 0x88, 0x98,
    0x66, 0x66, 0x77, 0x88, 0x98
};
```
the effect remains, although it is less "red"

with
```
static const unsigned char g_rfx_quantization_values[] =
{
    0x76, 0x77, 0x88, 0x98, 0xA9,
    0x76, 0x77, 0x88, 0x98, 0xA9
};
```
the effect is gone, but compression artefacts are visible

how do this values work? you already said that higher means less bits, but what do the five digits mean?

**Comment by jsorg71** [comment]
It's the 10 bands, see
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/3e9c8af4-7539-4c9d-95de-14b1558b902c
Setting them all to 6 means basically no quantize.  I don't think you can go < 6.

**Comment by akarl10** [comment]
I tried some values and I think this effect is if HH2 != HL2/LH2

anyhow, this are the values I use now and I think they are ok:
```
static const unsigned char g_rfx_quantization_values[] =
{
    0x66, 0x66, 0x77, 0x87, 0x98,
    0x76, 0x77, 0x88, 0x98, 0x99
};
```

**Comment by metalefty** [comment]
I see the similar scanline even between Windows to Windows RDP.

**Comment by akarl10** [comment]
@metalefty I've really never seen such a thing when connecting to a windows system.
But some quantization values seem to create such an effect and if @jsorg71 says higher numbers mean drop more bits I guess Windows adapts this values to the network conditions and it may also hit a "scanline" value.

What would be interesting is what values Windows uses and if Windows has a bandwidth/quantization mapping

**Comment by metalefty** [comment]
This is the scanline I see. Both client and server are connected via Wi-Fi and in the local network.

![image](https://user-images.githubusercontent.com/941609/200203017-ab154e86-eb2f-48e6-8e12-3b23301fe9be.png)

**Comment by metalefty** [comment]
Another screenshot. ![image](https://user-images.githubusercontent.com/941609/200204848-517da8ee-48e2-4be6-a620-ecb06c1d2601.png)
